repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python