# circleci config
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build dist
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install wheel
            python setup.py sdist bdist_wheel
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov=math_playground --doctest-modules
            coverage xml -o test-reports/coverage.xml
            coverage html -d htmlcov
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: dist
