# circleci config
version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Create environment
          command: conda env create -f environment.yml
      - run:
          name: mypy type checking
          command: |
            source activate math-env
            mypy pymathutils
      - run:
          name: check black formatting
          command: |
            source activate math-env
            black --check pymathutils/
      - run:
          name: build dist
          command: |
            source activate math-env
            conda install conda-build
            conda-build RECIPE_PATH ./conda.recipe --output-folder ./conda.dist
            python setup.py sdist bdist_wheel
      - run:
          name: run tests
          command: |
            source activate math-env
            pytest --cov=pymathutils --doctest-modules
            coverage xml -o test-reports/coverage.xml
            coverage html -d htmlcov
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: conda.dist/noarch/