# circleci config
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests --with-doctest --with-coverage --where math_playground/
            coverage xml -o test-reports/coverage.xml
      - store_test_results:
          path: test-reports
