{% set data = load_setup_py_data() %}

package:
  name: math_playground
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python

requirements:
  build:
    - python
  run:
    - python
